### ISSUE TITLE
Can't import 

### ISSUE THREAD

**Issue by Rested** [cubik-oss/stringmap-es5#2]
```Could not find a declaration file for module 'scalarmap-es5'``` 
I think this is because index.ts not in the package.json file list?

Also, when trying to import just numbermap as `import {NumberMap} from "scalarmap-es5/numbermap"` I get `Module parse failed: /Users/restd/PhpstormProjects/cubik-app/tsunami/node_modules/scalarmap-es5/numbermap.ts Unexpected token (2:22)`

**Comment by Rested** [comment]
I think the easiest fix would just be `export {StringMap, NarrowStringMap} from "./stringmap";` in the `index.ts`, and `index.ts` in the package.json files

**Comment by timruffles** [comment]
Definitely, whatever works! I pushed a new version. Bit rushed today so if you can take over that'd be perfect :)

**Comment by timruffles** [comment]
Also - add yourself to the authors ! Do you have an npm usename? Will add you there too
